# Generated by Django 4.2.29 on 2026-03-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_friendrequest_index_name_alignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_background_opacity",
            field=models.FloatField(default=1.0),
        ),
    ]