# Generated by Django 4.2.29 on 2026-04-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_update_rap_sleeve_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="level",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="profile",
            name="xp",
            field=models.PositiveIntegerField(default=0),
        ),
    ]